(require 'prelude-clojure)
(require 'prelude-emacs-lisp)
(require 'prelude-erlang)
(require 'prelude-elixir)
(require 'prelude-js)
(require 'prelude-lisp)
(require 'prelude-python)
(require 'prelude-rust)
(require 'prelude-scheme)
(require 'prelude-shell)
(require 'prelude-web)
(require 'prelude-css)
(require 'prelude-xml)
(require 'prelude-yaml)
(require 'prelude-company)
(require 'prelude-ivy)
;; (require 'prelude-helm)
;; (require 'prelude-helm-everywhere)
